fileRepositoryFolder: C:/Users/silviovutea/FileRepository
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: -1 # No file size limit
      max-request-size: -1  # No limit on request size
